import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import project.ConnectionProvider;


public class Managment extends javax.swing.JFrame {

    /**
     * Creates new form NewUser
     */
    public Managment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("managment");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Management");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("userID :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 152, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("accessinno :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 152, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("status :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        jButton1.setText("modify");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 73, -1));

        jButton2.setText("cancle");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 73, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "reserve", "borrow", "return" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 150, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\naser farajzade\\Pictures\\library project\\new.jpg")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String userId = jTextField1.getText();
        String accessinno = jTextField2.getText();
        int statusId = jComboBox1.getSelectedIndex();
        //reserve = 0
        //borrow = 1
        //return = 2
        
        String userIdCheckQuery = "select * from users where userID = "+ userId;
        String accessinnoCheckQuery = "select * from books where accessinno = "+ accessinno;
        String updateRETURNQuery = "UPDATE borrows SET statusID = "+ statusId + " WHERE userID = " + userId + " AND accessinno = " + accessinno;
        String isBookAvailableQuery = "select * from borrows WHERE accessinno = " + accessinno + " AND borrows.statusID IN (0,1)";
        String addBORROWQuery = "insert into borrows values("+userId+","+accessinno+","+statusId+")";
        String wasBorroedOrReserved = "select * from borrows WHERE accessinno = " + accessinno + " AND borrows.statusID IN (0,1) AND userID = "+ userId;
        
        Connection con = ConnectionProvider.getCon();
        Statement statement;
        
       
        try {
            statement = con.createStatement();
            ResultSet resultSet = statement.executeQuery(userIdCheckQuery);
            if(resultSet.next()){
                resultSet.close();
                
                ResultSet resultSet2 = statement.executeQuery(accessinnoCheckQuery);
                if(resultSet2.next()){
                    resultSet2.close();
                    
                    if(statusId == 2){
                        //return book to library
                        ResultSet resultSet4 = statement.executeQuery(wasBorroedOrReserved);
                        if(resultSet4.next()){
                            resultSet4.close();
                            statement.executeUpdate(updateRETURNQuery);
                            JOptionPane.showMessageDialog(null , "suceccfully returned");
                            setVisible(false);
                            new Managment().setVisible(true);
                        }else{
                            JOptionPane.showMessageDialog(null , "you didn't borrowed or reserved this book");
                            setVisible(false);
                            new Managment().setVisible(true);
                        }
                        
                    }else{
                        //borrow or reserve
                        ResultSet resultSet3 = statement.executeQuery(isBookAvailableQuery);
                        if(resultSet3.next()){
                            resultSet3.close();
                            //borrowed or reserved
                            JOptionPane.showMessageDialog(null , "the book was borroed or reserved");
                            setVisible(false);
                            new Managment().setVisible(true);
                        }else{
                            try{
                                statement.executeUpdate(addBORROWQuery);    
                            }catch(Exception e){
                                statement.executeUpdate(updateRETURNQuery);
                            }
                            
                            JOptionPane.showMessageDialog(null , "info successfully added");
                            setVisible(false);
                            new Managment().setVisible(true);
                        }
                    }
                    
                }else{
                    JOptionPane.showMessageDialog(null , "book is not in database");
                    setVisible(false);
                    new Managment().setVisible(true);
                }
                
            }else{
                JOptionPane.showMessageDialog(null , "user not found");
                setVisible(false);
                new Managment().setVisible(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Managment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    
    
    private void jButton1ActionPerformed1(java.awt.event.ActionEvent evt) {
    
        String userId = jTextField1.getText();
        String accessinno = jTextField2.getText();
        int statusId = jComboBox1.getSelectedIndex();
        //reserve = 0
        //borrow = 1
        //return = 2
        
        String userIdCheckQuery = "select * from users where userID = "+ userId;
        String accessinnoCheckQuery = "select * from books where accessinno = "+ accessinno;
        String updateRETURNQuery = "UPDATE borrows SET statusID = "+ statusId + " WHERE userID = " + userId + " AND accessinno = " + accessinno;
        String isBookAvailableQuery = "select * from borrows WHERE accessinno = " + accessinno + " AND borrows.statusID IN (0,1)";
        String addBORROWQuery = "insert into borrows values("+userId+","+accessinno+","+statusId+")";
        
        Connection con = ConnectionProvider.getCon();
        Statement statement;
        
       
        try {
            statement = con.createStatement();
            ResultSet resultSet = statement.executeQuery(userIdCheckQuery);
            if(resultSet.next()){
                resultSet.close();
                
                ResultSet resultSet2 = statement.executeQuery(accessinnoCheckQuery);
                if(resultSet2.next()){
                    resultSet2.close();
                    
                    if(statusId == 2){
                        //return book to library
                        statement.executeUpdate(updateRETURNQuery);
                        System.out.println("suceccfully returned");
                    }else{
                        //borrow or reserve
                        ResultSet resultSet3 = statement.executeQuery(accessinnoCheckQuery);
                        if(resultSet3.next()){
                            resultSet3.close();
                            //borrowed or reserved
                            System.out.println("borrowed or reserved");
                        }else{
                            System.out.println("bia");
                            statement.executeUpdate(addBORROWQuery);
                            JOptionPane.showMessageDialog(null , "info successfully added");
                            setVisible(false);
                            new Managment().setVisible(true);
                        }
                    }
                    
                }else{
                    System.out.println("book is not in database");
                }
                
            }else{
                System.out.println("user not found");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Managment.class.getName()).log(Level.SEVERE, null, ex);
        }


      
    
    }
    
    
    
    
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Managment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
